apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
  labels:
    app: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: andrepereira21/n8n-puppeteer:2.0.2
          ports:
            - containerPort: 5678
          env:
            - name: N8N_PROXY_HOPS
              value: "1"
            - name: N8N_RUNNERS_ENABLED
              value: "true"
            - name: N8N_RUNNERS_MODE
              value: "external"
            - name: N8N_TASK_BROKER_PORT
              value: "5679"
            - name: N8N_CUSTOM_EXTENSIONS
              value: n8n-nodes-puppeteer
            - name: N8N_HOST
              value: "n8n.local"
            - name: WEBHOOK_URL
              #value: "http://n8n.local/"
              value: "https://andrepereira.tec.br"
            - name: N8N_PROTOCOL
              value: "http"
            - name: N8N_PORT
              value: "5678"
            - name: N8N_BASIC_AUTH_ACTIVE
              value: "true"
            - name: N8N_BASIC_AUTH_USER
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: N8N_BASIC_AUTH_USER
            - name: N8N_BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: N8N_BASIC_AUTH_PASSWORD
            - name: N8N_SECURE_COOKIE
              value: "false"
            - name: PUPPETEER_EXECUTABLE_PATH
              value: /usr/bin/chromium-browser
            - name: GENERIC_TIMEZONE
              value: "America/Sao_Paulo"
            - name: N8N_RUNNERS_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: N8N_RUNNERS_AUTH_TOKEN

          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n
        
        - name: task-runner-python
          image: n8nio/runners:2.0.2
          imagePullPolicy: IfNotPresent
          env:
            - name: N8N_TASK_BROKER_URL
              value: "ws://127.0.0.1:5679" # Conecta no container principal via localhost
            # Se você definir um segredo, adicione-o aqui também
            - name: N8N_RUNNERS_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: N8N_RUNNERS_AUTH_TOKEN
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"

      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-pvc